### ISSUE TITLE
about encode_image.py

### ISSUE THREAD

**Issue by zhanghongyong123456** [GreenLimeSia/Real-Image-Manipulation-under-Domain-Guided-Noise-Optimization-Mechanism#1]
![004](https://user-images.githubusercontent.com/48466610/119780438-66c2a380-befc-11eb-9ee6-95d68153ebba.png)
1：I want to know which model to use,
2： PSP or StyleGan2 for the base environment,

**Comment by GreenLimeSia** [comment]
Hi @zhanghongyong123456 , I do not find the above line code in encode_image.py. Can you give me some details? 

Maybe you can do this:  python encode_image.py --src_dir ./align_images/ --result_file ./result_file --dlatent_dir ./dlatent_dir/      
  --size 1024  --ckpt ./networks/stylegan2-ffhq-config-f.pt  --id_ckpt ./networks/dni_identity.pt  
  --se_ckpt ./networks/dni_sematic.pt  --mode DNI --step your_step_size

Please make sure you have its corresponding dir, such as ./align_images/. About ckpt, you can find it in [here](https://drive.google.com/file/d/1RBCRmwCmuvG51o0B05YyxnjJU2bl5hW6/view?usp=sharing), and id_ckpt in [here](https://drive.google.com/file/d/1jiroHFR6qdlO2808Rua_l50s3xm13ebj/view?usp=sharing), se_ckpt in [here](https://drive.google.com/file/d/1dalUrcYeqxj1aWnrlxEJ5cJQrKIjwIqo/view?usp=sharing).

Hope it is useful for you!

Best wishes.

**Comment by zhanghongyong123456** [comment]
sorry,i should show more details about this problem,
![image](https://user-images.githubusercontent.com/48466610/119921790-36811080-bfa1-11eb-95c2-e7b4a4e858e3.png)

**Comment by GreenLimeSia** [comment]
For this issue, you must make sure your GPU memory is larger than 16G. @zhanghongyong123456
