### ISSUE TITLE
About how to use play_with_dlatent.py

### ISSUE THREAD

**Issue by roger799** [GreenLimeSia/Real-Image-Manipulation-under-Domain-Guided-Noise-Optimization-Mechanism#2]
Hi,thank you for your exciting work!When I use the play_with_dlatent.py,I find "synth_img = generator(latent_vector)" seems to not work,just like Initialize every time when I use, Could you give me some advices to use,I would be happy it you could shed some light.

**Comment by GreenLimeSia** [comment]
Hi, I do not understand the problem for you. I guess you may want to know how to use this code?  generate_image(latent_vector, generator) is a function of generate an image with a pre-trained Stylegan2 model, the mode is model.eval().  In order to use this code,  you should obtain a latent code that needs to played with shape (18, 512).  Then use latent directions to play them. The Gs model is available in https://drive.google.com/file/d/10pa6aXI-V8qNsWu7kdE2cIAQDAe8ixNa/view?usp=sharing.

**Comment by roger799** [comment]
> Hi, I do not understand the problem for you. I guess you may want to know how to use this code? generate_image(latent_vector, generator) is a function of generate an image with a pre-trained Stylegan2 model, the mode is model.eval(). In order to use this code, you should obtain a latent code that needs to played with shape (18, 512). Then use latent directions to play them. The Gs model is available in https://drive.google.com/file/d/10pa6aXI-V8qNsWu7kdE2cIAQDAe8ixNa/view?usp=sharing.

Thank you for your reply, Maybe I didn’t express it clearly，when I use "encoder_image_new.py",for 2000 iterations,the result is left,when I use "play_with_dlatent.py",use a latent code to generate an image with a pre-trained Stylegan2 model,the result is right,Obviously the result is wrong，I want to know what went wrong，please help me, thank you !

![optimizer_2200](https://user-images.githubusercontent.com/66153317/91640341-6bcaf300-ea4f-11ea-98df-9c6dafb4e582.png)
![optimizer_0](https://user-images.githubusercontent.com/66153317/91640347-7ab1a580-ea4f-11ea-817a-853ab0d0dd94.png)

**Comment by GreenLimeSia** [comment]
First, in "encoder_image_new.py", we can use the latent code initialized with image_to_latent or initialize the latent code with torch.zero(). If we use the latent code initialized with torch.zero(), we will encounter the problem of the latent code is not aligned with the semantic knowledge encoded in StyleGAN2 latent space. Second, in "play_with_dlatent.py", the "coeffs" is not fixed, we should adjust the rate according to different attributes. I hope that can help you!

**Comment by roger799** [comment]
> First, in "encoder_image_new.py", we can use the latent code initialized with image_to_latent or initialize the latent code with torch.zero(). If we use the latent code initialized with torch.zero(), we will encounter the problem of the latent code is not aligned with the semantic knowledge encoded in StyleGAN2 latent space. Second, in "play_with_dlatent.py", the "coeffs" is not fixed, we should adjust the rate according to different attributes. I hope that can help you!

Thank you，Below is the code I used：
###################
    path_model = './Gs.pth'
    G = stylegan2.models.load(path_model)
    assert isinstance(G, stylegan2.models.Generator), 'Model type has to be ' + \
                                                      'stylegan2.models.Generator. Found {}.'.format(type(G))
    G.to(device)
    face_latent = torch.from_numpy(np.load('dlatents/optimizer.npy')).squeeze().to(device)
    face_latent = face_latent.reshape((1, 18, 512))
    synth_img = G(face_latent)
    synth_img = (synth_img + 1.0) / 2.0 # 0~1
    save_image(synth_img.clamp(0, 1), os.path.join(path_result, "000.jpg"))
#####################
the result "000.jpg" is the picture posted above(the second one),I use "encoder_image_new.py" to generate 'dlatents/optimizer.npy', Is there something wrong with my usage?
Simultaneously，I tried to use the latent code initialized with image_to_latent，but the result is the same as use the latent code initialized with torch.zero(),Can you share the "image_to_latent.pt",I will try it，thank you ！In short, I can’t reproduce your results.

**Comment by GreenLimeSia** [comment]
The image_to_latent model is needed to pre-trained, you can follow https://github.com/jacobhallberg/pytorch_stylegan_encoder or domain_encoder to train your own image_to_latent. 
About the pre-trained image_to_latent model, we will apply it to other studies, which will not be open for a while. In addition, the paper is under writing and we need to do many other experiments. Thank you for your attention!

**Comment by roger799** [comment]
> The image_to_latent model is needed to pre-trained, you can follow https://github.com/jacobhallberg/pytorch_stylegan_encoder or domain_encoder to train your own image_to_latent.
> About the pre-trained image_to_latent model, we will apply it to other studies, which will not be open for a while. In addition, the paper is under writing and we need to do many other experiments. Thank you for your attention!

Ok i will try it, thanks！
