### ISSUE TITLE
about   colab 

### ISSUE THREAD

**Issue by zhanghongyong123456** [GreenLimeSia/Real-Image-Manipulation-under-Domain-Guided-Noise-Optimization-Mechanism#2]
![image](https://user-images.githubusercontent.com/48466610/119922778-1a7e6e80-bfa3-11eb-9e40-1b9135311e87.png)
when i using  this colab

**Comment by GreenLimeSia** [comment]
You should access Google via VPN. And copy this project as your own. Then just interesting do it.
